services:
  - type: web
    name: saldox
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: saldox-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: saldox-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: saldox-db
          property: password

databases:
  - name: saldox-db
    plan: free
